name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'    
  push:
    branches:
      - 'main'  
  create:
    branches:
      - 'main'
    tags:
      - '**'

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python
      run: |
        pip install -e .
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Run tests
      run: |
        python -m pytest --durations=20 -v test/ ot/ --doctest-modules --color=yes --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: gemini-clustering/GemClus
